import { randomId } from './random-id';

export const companies = [
  {
    name: 'ТЕСТ1',
    address: '4 Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
    ],
  },
  {
    name: 'ТЕСТ2',
    address: '23 Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
    ],
  },
  {
    name: 'ТЕСТ3',
    address: '322 Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
    ],
  },
  {
    name: 'ТЕСТ4',
    address: '11 Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },{
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },

      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
    ],
  },
  {
    name: 'ТЕСТ5',
    address: '322 Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
    ],
  },
  {
    name: 'ТЕСТ6',
    address: '3 Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },

      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
    ],
  },
  {
    name: 'ТЕСТ7',
    address: 'test Main Street',
    id: randomId(),
    employees: [
      {
        id: randomId(),
        firstName: 'Иван',
        lastName: 'Иванов',
        position: 'Инженер-программист',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
      {
        id: randomId(),
        firstName: 'Александра',
        lastName: 'Смирнова',
        position: 'Менеджер проектов',
      },
      {
        id: randomId(),
        firstName: 'Дмитрий',
        lastName: 'Петров',
        position: 'Аналитик данных',
      },
      {
        id: randomId(),
        firstName: 'Елена',
        lastName: 'Сидорова',
        position: 'Дизайнер UX/UI',
      },
      {
        id: randomId(),
        firstName: 'Михаил',
        lastName: 'Кузнецов',
        position: 'Маркетолог',
      },
      {
        id: randomId(),
        firstName: 'Ольга',
        lastName: 'Васильева',
        position: 'Менеджер по персоналу',
      },
      {
        id: randomId(),
        firstName: 'Илья',
        lastName: 'Смирнов',
        position: 'Разработчик программного обеспечения',
      },
      {
        id: randomId(),
        firstName: 'София',
        lastName: 'Попова',
        position: 'Бизнес-аналитик',
      },
      {
        id: randomId(),
        firstName: 'Кирилл',
        lastName: 'Морозов',
        position: 'Менеджер по продукту',
      },
      {
        id: randomId(),
        firstName: 'Анна',
        lastName: 'Новикова',
        position: 'Контент-менеджер',
      },
      {
        id: randomId(),
        firstName: 'Даниил',
        lastName: 'Козлов',
        position: 'Финансовый аналитик',
      },
      {
        id: randomId(),
        firstName: 'Алина',
        lastName: 'Лебедева',
        position: 'Специалист по поддержке клиентов',
      },
      {
        id: randomId(),
        firstName: 'Егор',
        lastName: 'Соколов',
        position: 'Менеджер по продажам',
      },
      {
        id: randomId(),
        firstName: 'Мария',
        lastName: 'Крылова',
        position: 'Графический дизайнер',
      },
      {
        id: randomId(),
        firstName: 'Лев',
        lastName: 'Громов',
        position: 'Инженер по контролю качества',
      },
      {
        id: randomId(),
        firstName: 'Ангелина',
        lastName: 'Белова',
        position: 'Менеджер по операциям',
      },
      {
        id: randomId(),
        firstName: 'Никита',
        lastName: 'Мельников',
        position: 'IT-специалист',
      },
      {
        id: randomId(),
        firstName: 'Елизавета',
        lastName: 'Кудрявцева',
        position: 'Специалист по цифровому маркетингу',
      },
      {
        id: randomId(),
        firstName: 'Александр',
        lastName: 'Ковалев',
        position: 'Веб-разработчик',
      },
      {
        id: randomId(),
        firstName: 'Полина',
        lastName: 'Захарова',
        position: 'Координатор проекта',
      },
      
    ],
  }
];
